on:
  push:
    branches:
      - development
name: Development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn

      - name: Build Site
        run: yarn build

      - name: "Build Lambda"
        run: |
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/hartelo/lambda.git lambda && \
          cd lambda && \
          yarn && \
          yarn build
