on:
  push:
    branches:
      - master
name: Staging Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn

      - name: Build Site
        run: yarn build

      - name: "Lambda Function"
        run: |
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/hartelo/lambda.git lambda && \
          cd lambda && \
          yarn && \
          yarn build && \
          mv ./lib/index.js ../copyLandingPageStagingToProd.js

      - name: "Terraform File"
        run: |
          curl -H 'Authorization: token ${{ secrets.ACCESS_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3.raw' \
          -O \
          -L ${{ secrets.ENV_REPO_URL }}

      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: "init"

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: "plan"

      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: "apply"

      - name: "Sync to S3 Staging Bucket"
        run: aws s3 sync public ${{ secrets.STAGING_BUCKET }}
